version: "3"
services:
  api:
    image: golang:1.16.6-buster
    tty: true
    volumes:
    - .:/src
    working_dir: /src
    ports:
    - 8080:8080
    - 8081:8081
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
    - ./docs/apidocs.swagger.json:/usr/share/nginx/html/apidocs.swagger.json
    environment:
      API_URL: ./apidocs.swagger.json
    ports:
    - 9000:8080
